Repository CS2103JAN2018-T15-B3/main, pull requests merged in 2018-04, with the labels that each got.

#77 [Milestone 1.4] Chan Jin Jia, Updated User Doc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/LoadDirectionsEvent.java
Labels: priority.medium, type.documentation

#79 [Milestone 1.4] Chan Jin Jia, Additional Enhancements
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/LoadDirectionsEvent.java
  src/main/java/seedu/address/commons/events/ui/RemoveDirectionsEvent.java
  src/main/java/seedu/address/commons/events/ui/UpdateNumberOfButtonsEvent.java
  src/main/java/seedu/address/commons/exceptions/InvalidCalendarEventCountException.java
  src/main/java/seedu/address/logic/MapManager.java
  src/main/java/seedu/address/logic/OAuthManager.java
  src/main/java/seedu/address/logic/commands/NavigateCommand.java
  src/main/java/seedu/address/logic/commands/ShowScheduleCommand.java
  src/main/java/seedu/address/logic/parser/NavigateCommandParser.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/DailySchedulerPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MapPanel.java
  src/main/java/seedu/address/ui/PersonDetailsPanel.java
  src/main/resources/view/DailySchedulerPanel.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MapPanel.fxml
  src/main/resources/view/PersonDetailsPanel.fxml
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.medium, type.enhancement

#80 [Milestone V1.4] Added bug fixes
  Collate-TUI.jar
  collated/test/kaisertanqr.md
  docs/ContactUs.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleUsersUtil.java
  src/test/java/seedu/address/logic/commands/ChangeUserPasswordCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateUserCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteUserCommandTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/parser/ChangeUserPasswordCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CreateUserCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteUserCommandParserTest.java
Labels: priority.high, type.bug, type.documentation

#102 Kaiser [Milestone V1.5] Added add session logs command and logic
  src/main/java/seedu/address/logic/commands/AddSessionLogCommand.java
  src/main/java/seedu/address/logic/commands/ChangeUserPasswordCommand.java
  src/main/java/seedu/address/logic/parser/AddSessionLogCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/SessionLogs.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ChangeUserPasswordCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateUserCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteUserCommandTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
Labels: type.feature

#107 [Milestone 1.5rc] Chan Jin Jia, Refactored MapManager and Added Removal of Directions
  src/main/java/seedu/address/commons/events/ui/ResetDirectionsEvent.java
  src/main/java/seedu/address/logic/MapManager.java
  src/main/java/seedu/address/logic/commands/NavigateCommand.java
  src/main/java/seedu/address/logic/commands/ShowScheduleCommand.java
  src/main/java/seedu/address/logic/map/MapManager.java
  src/main/java/seedu/address/logic/map/MyDirectionsServiceCallback.java
  src/main/java/seedu/address/logic/map/MyGeocodingServiceCallback.java
  src/main/java/seedu/address/ui/DailySchedulerPanel.java
  src/main/java/seedu/address/ui/MapPanel.java
Labels: priority.high, type.enhancement

#110 [Milestone 1.5rc] Chan Jin Jia, Display Scheduled Event
  src/main/java/seedu/address/commons/events/ui/DailyScheduleShownChangedEvent.java
  src/main/java/seedu/address/logic/OAuthManager.java
  src/main/java/seedu/address/logic/commands/ShowScheduleCommand.java
  src/main/java/seedu/address/ui/DailySchedulerPanel.java
  src/main/java/seedu/address/ui/ScheduledEventCard.java
  src/main/resources/view/DailySchedulerPanel.fxml
  src/main/resources/view/ScheduledEventCard.fxml
Labels: priority.high, type.feature

#111 [Milestone 1.5rc] Chan Jin Jia, Display Session Reports
  src/main/java/seedu/address/commons/events/ui/ShowUpdatedSessionLogEvent.java
  src/main/java/seedu/address/logic/OAuthManager.java
  src/main/java/seedu/address/logic/commands/AddSessionLogCommand.java
  src/main/java/seedu/address/ui/PersonDetailsPanel.java
  src/main/java/seedu/address/ui/ScheduledEventCard.java
  src/main/resources/view/PersonDetailsPanel.fxml
  src/main/resources/view/ScheduledEventCard.fxml
Labels: priority.high, type.feature

#113 [Milestone 1.5rc] Chan Jin Jia, Update Guides and SampleDataUtil, Added PPP
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/jaronchan.jpg
  docs/team/jaronchan.adoc
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.documentation

#114 [Milestone 1.5rc] Updated jaronchan.adoc and added HTML version
  docs/team/jaronchan.adoc
  docs/team/jaronchan.html
Labels: type.documentation

#120 [Milestone 1.5] Chan Jin Jia, Updated GUI and CSS
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/commands/AddSessionLogCommand.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/DailySchedulerPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/images/slap-brand.jpg
  src/main/resources/view/DailySchedulerPanel.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/LoginStatusBar.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDetailsPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.medium, type.enhancement

#134 [Milestone 1.5] Chan Jin Jia, Address Issues
  src/main/java/seedu/address/commons/events/ui/RefreshDetailsPanelEvent.java
  src/main/java/seedu/address/logic/commands/AddSessionLogCommand.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/commands/NavigateCommand.java
  src/main/java/seedu/address/logic/parser/NavigateCommandParser.java
  src/main/java/seedu/address/ui/DailySchedulerPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonDetailsPanel.java
  src/main/resources/view/Extensions.css
Labels: priority.high, type.bug
